language: node_js
node_js:
- '8'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - JOBS=1
  - secure: 3e7eN+DwyxcK7eR8GrXstsWNb3sjRfiWDno3LuOnkkB7EIR5X//eWyQ8GYRZhozHTzabvJHdtgunU2fESMgsKtqeZLy5pYRDA/6D6OAEi2p+bfzqDZqRStLF9p+TKtAOrWlpQrG4NY6/UFCVmDvOEjpsCDNdL6tx/gG621LCmo6al0qWPvVYJBOSxfVdcEeBJZgJnfr8xGv86LwyI7/ZQ+fVTzvBt75aJCyqG/WivMSQfOemJLnvarrL7qUxCc/+sYVRV8YxmbY3gJiBmAJKi/XyHhcCXTsuzfZkApXU+XM8B8a0g5VpLxC1wUBWjGHd2E1ePCkqw4JDI/A0X/7BJY2wGDo1t4XWUBGzYaUstcqe+LgmSCQTEKAmLdywqNaMGQLPDe02/NDGQDFlFrwhS/JFzWdCiPdRpydToz794FZKrtwqsch5VpLwRfz5Qrsi7rDw4NEG/sY/u8EEjoaSUkuJyFDm4Y0s8LukBezJ4SEUbxenXbLqQ/3rx6fmdtRDe1aX5Hdi+EXKP27ptBLXtAYTAiXeJP4eYUEQVjT5kw9pRY2VA5DcMLGZQWGbmxQw1SsZJ2L1j+TIPDCglIE9fkN9OnCwIIydgqhESuy4jvzWVU3XglXpX5EO4NDJCe9PMqfrUB+d+KMONvhgABFgFRicStXz7DbRuPce0dzxYro=
before_install:
- npm config set spin false
script:
- npm run lint:hbs
- npm run lint:js
- npm test
deploy:
  provider: heroku
  api_key:
    secure: gOu33Rxjy/UIAIsqPyskOYb621tDKkgQAx1PJI8TNr1QdY4mDTokcgchbINKj2bpGwaEBkgIo9CxpbuwetLaEoO8W1WG8hEL+gGKapY3JwvnJVku17E+PdxtBaeHxjQTxjq6Sb5gBdZ2w/aFMTSM6wdT4G6E0M4hsqcNoVwVbR3ZOjSaTIAZX+WR9IZadwGY/o8K7mBeAFpUBkfJnrI2FXMfa7Bj0n01TCOn008RFmgPBgN65+jZxf5vRuLrNo/S1igSVwn/QzMILc+Sn9YnOltkajlqGfP+CKwAwAzHP9EU/Z2g5kbqyMBs8wDW2G5sGUiTj83jYsK6FkoC1Y/FC7CS2Dn+SCKbJndRXMmV0aKk8te83blN4mZMRdHb9tZGvuvYyEsgNzuwzFpT4tOehj+ZB2jKe1XU/YkYhiCc2okQDczU/lUca3MwEwU+rCFBM/HEjdxaGWirhA19A9qAIwUNYw0mS9bod7bZTf+6p2TrSoKGqcyp+EUjDdrrmJPSCbUPwvUK/xHXDhtr0uVzkPTypAR3aN2CAb325/6intstQAUoWcO5RoFyLZv6NtPoSSE70WXXu3R61w5WxLtGh7UBSNzSIxCYIj/UPWr4leQdOM0frKH0ui06tCNsqU+i+3+qIPHCNAIJ+XH5oF9cGW16A8d5KAyEPEUkFYxyoJc=
  app: baozi-web
  on:
    repo: rreckonerr/baozi-web
