language: node_js
node_js:
- '8'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - JOBS=1
  - secure: 3e7eN+DwyxcK7eR8GrXstsWNb3sjRfiWDno3LuOnkkB7EIR5X//eWyQ8GYRZhozHTzabvJHdtgunU2fESMgsKtqeZLy5pYRDA/6D6OAEi2p+bfzqDZqRStLF9p+TKtAOrWlpQrG4NY6/UFCVmDvOEjpsCDNdL6tx/gG621LCmo6al0qWPvVYJBOSxfVdcEeBJZgJnfr8xGv86LwyI7/ZQ+fVTzvBt75aJCyqG/WivMSQfOemJLnvarrL7qUxCc/+sYVRV8YxmbY3gJiBmAJKi/XyHhcCXTsuzfZkApXU+XM8B8a0g5VpLxC1wUBWjGHd2E1ePCkqw4JDI/A0X/7BJY2wGDo1t4XWUBGzYaUstcqe+LgmSCQTEKAmLdywqNaMGQLPDe02/NDGQDFlFrwhS/JFzWdCiPdRpydToz794FZKrtwqsch5VpLwRfz5Qrsi7rDw4NEG/sY/u8EEjoaSUkuJyFDm4Y0s8LukBezJ4SEUbxenXbLqQ/3rx6fmdtRDe1aX5Hdi+EXKP27ptBLXtAYTAiXeJP4eYUEQVjT5kw9pRY2VA5DcMLGZQWGbmxQw1SsZJ2L1j+TIPDCglIE9fkN9OnCwIIydgqhESuy4jvzWVU3XglXpX5EO4NDJCe9PMqfrUB+d+KMONvhgABFgFRicStXz7DbRuPce0dzxYro=
before_install:
- npm config set spin false
script:
- npm run lint:hbs
- npm run lint:js
- npm test
deploy:
  provider: heroku
  api_key:
    secure: JwPNSUD1li1DaExOaGkAETfofEA9yrgnCW36XATo8R7muh/bhX8j1TXW0FlvQ/2QtoFSv2R6whze+tvZsR+GfOY5UExG1jeu/AZf38Jjc7qwODvW6A/EREorB5i97jKZQx+Oiz20R4c6efPsAjo1eINfKk+20ZkmAjWIz26RaclDd+HqtndNWfuKR4ml4x2wsxuQY/YUhxDQ9DpxmKefoRCS/PBuhOe5CAj/2fRqWfsgcMjTKFujPui4ccci1n5dzCOvaCFsUrPJYoR1M1685PSLWlHrhawluztZuA11F5KAw1NsvHELXgl83PJji+Io8kC2McMVjiNxPecFqPMdRP7chH78IuPWIL7Ip1gEf04y5ilrNiRuCn6MCIXVGf1zihGjfz+LzzeC3wQTN0G/AcVNtfSkG1oGZHB+VXxEcqbUVFw0LeLL1UE7ST5GhSf7pg88zoEJicppOz6z6pFtpTWecuxGTLXWe9Hp4FSPR7UUS84J4EXcSDuikH2giwLEezj70DyCbCcaWeC2VVvwRl1tOPEai75dTRDgqinbyDxC71pKBqcSrJbNNqJ1L2JABUbvVPGfBN+6Rhyxu93LAtK/dN9P5r6qmhiI3dck3RaFotxBoLevRJSvTNgJW3ZY1R/IOF0ac5pM75twjDzlTbIAxtbyqkK9i5s9PYmmZCI=
  app: baozi-web
  on:
    repo: rreckonerr/baozi-web
