language: node_js
node_js:
- '8'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - JOBS=1
  - secure: 3e7eN+DwyxcK7eR8GrXstsWNb3sjRfiWDno3LuOnkkB7EIR5X//eWyQ8GYRZhozHTzabvJHdtgunU2fESMgsKtqeZLy5pYRDA/6D6OAEi2p+bfzqDZqRStLF9p+TKtAOrWlpQrG4NY6/UFCVmDvOEjpsCDNdL6tx/gG621LCmo6al0qWPvVYJBOSxfVdcEeBJZgJnfr8xGv86LwyI7/ZQ+fVTzvBt75aJCyqG/WivMSQfOemJLnvarrL7qUxCc/+sYVRV8YxmbY3gJiBmAJKi/XyHhcCXTsuzfZkApXU+XM8B8a0g5VpLxC1wUBWjGHd2E1ePCkqw4JDI/A0X/7BJY2wGDo1t4XWUBGzYaUstcqe+LgmSCQTEKAmLdywqNaMGQLPDe02/NDGQDFlFrwhS/JFzWdCiPdRpydToz794FZKrtwqsch5VpLwRfz5Qrsi7rDw4NEG/sY/u8EEjoaSUkuJyFDm4Y0s8LukBezJ4SEUbxenXbLqQ/3rx6fmdtRDe1aX5Hdi+EXKP27ptBLXtAYTAiXeJP4eYUEQVjT5kw9pRY2VA5DcMLGZQWGbmxQw1SsZJ2L1j+TIPDCglIE9fkN9OnCwIIydgqhESuy4jvzWVU3XglXpX5EO4NDJCe9PMqfrUB+d+KMONvhgABFgFRicStXz7DbRuPce0dzxYro=
before_install:
- npm config set spin false
script:
- npm run lint:hbs
- npm run lint:js
- npm test
deploy:
  provider: heroku
  api_key:
    secure: KpAoN61P+P2KBaWex/8zlfeBwhsdvx+CubauQqN9Lef4KE7sMCIcwYENOz7sxw+5yxAXhY3dOAyoS0t0sFfzsNeeE5Y2S7LNgNfnCCacubMSWlY2HuGchEQl1Tf7JtmfisQwWEC2soAtjiULk2hWa29In+Y2q5n4DHo0wgT6ElIleBDeP32Kq0JsfJykS+faEoTBD65dslvW9k3cR9FmVmxA2Knk/D8vsst6NuUbGcrRmc+bVrLoh6ujw3QK3cWscZUCrv3hgabzxYjEK007rZVxtkenE7COrH++wpE7vnwLsP6TpFSottN4vhJARxgzSxTYbqMBhrgKmgEh+QZhSoC/KfE3wkprBysJW/Qvs0Y6FsJE2HR243+b0XqfldvPrUuKf3fRV/utArzhMF0iQa2UbmF42E0ypTdktrrTdoT43Awg3H/7sWIalPqJdcpGqjZaT0WHBbI/6zD7nOH9+Q/wiLEl2dI3tNsoFlG8WIWNX/VpBn+aTrU8MAV13mguLp9O/faQ7BZBS1j9w2GfgR8Qz6qHl8uiI3z81c6rxK3UAp+eVklb3VNwogbULCZRZ6kT8Tdz75o+v4TGnPOHmfuU91wuuyafzWajNNFqs7hn0+60aKgSl1/8c9Tsx9ulAOZrONBLd/Ud6fygLhbHUVlZBsE4DPJc5GuavWiouZ4=
  app: baozi-blog
  on:
    repo: rreckonerr/baozi-web
